Repository thanhpd/OpenTracks-Winter-SOEN-6431_2024, pull requests merged in 2024-02, with the labels that each got.

#16 #Issue20 - Replace this "switch" statement by "if" statements to increase readability.
  src/main/java/de/dennisguse/opentracks/ui/markers/MarkerEditActivity.java
Labels: task

#23 Refactor: Change type of 'items' to interface 'List' from implementat…
  src/main/java/de/dennisguse/opentracks/ui/aggregatedStatistics/FilterDialogFragment.java
Labels: Technical Debt

#28 Add a private constructor to hide the implicit public one
  src/main/java/de/dennisguse/opentracks/ui/customRecordingLayout/RecordingLayoutIO.java
Labels: Group 2, Technical Debt

#30 Replace this usage of Stream.collect(Collectors.toList()) with Stream.toList()
  src/main/java/de/dennisguse/opentracks/ui/customRecordingLayout/RecordingLayout.java
Labels: Group 2, Technical Debt

#25 Add the missing deprecated Javadoc tag
  src/main/java/de/dennisguse/opentracks/ui/intervals/IntervalsFragment.java
Labels: Group 2, Technical Debt

#37 Update ScrollVisibleViews to use inclusive range for visible views
  src/main/java/de/dennisguse/opentracks/ui/util/ScrollVisibleViews.java
Labels: task, Group 2, Technical Debt
